version: '3'

volumes:
  api-db-data:

services:

  api-db:
      image: postgres
      restart: unless-stopped
      environment:
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      volumes:
        - api-db-data:/var/lib/postgresql/data
      ports:
        - '${POSTGRES_PORT}:5432'

  api:
    build:
      context: .
    environment:
      SERVER_PORT: ${SERVER_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_HOST: db-api
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      KEYCLOAK_MIDDLEWARE_RESOURCE: ${KEYCLOAK_MIDDLEWARE_RESOURCE}
      KEYCLOAK_MIDDLEWARE_REALM: ${KEYCLOAK_MIDDLEWARE_REALM}
      KEYCLOAK_MIDDLEWARE_SERVER_URL: ${KEYCLOAK_MIDDLEWARE_SERVER_URL}
      KEYCLOAK_MIDDLEWARE_REALM_PUBLICKEY: ${KEYCLOAK_MIDDLEWARE_REALM_PUBLICKEY}
    depends_on:
      - api-db
    ports:
      - '${SERVER_PORT}:3030'
